name: build-and-test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run package
      - name: test
        run: npm run test
      - name: Publish Test Report
        uses: ./
        with:
          report-path: './ctrf/*.json'
          test-report: true
          previous-results-report: true
          write-ctrf-to-file: ./ctrf/new-ctrf-report.json
          insights-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
      - name: Upload CTRF Report
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ./ctrf/new-ctrf-report.json
        if: always()